### ISSUE TITLE
Arm版Homebrewの場合にtransコマンドが見えない

### ISSUE THREAD

**Issue by waku1123** [nkmr-jp/alfred-quick-translate#2]
M1 macで実行した場合にtransコマンドが見えない
```
translate.sh: line 23: trans: command not found
```

[translate.sh#6](https://github.com/nkmr-jp/alfred-quick-translate/blob/master/translate.sh#L6)にArm版Homebrewのパス(/opt/homebrew/bin)が含まれていないので、transコマンドが見えない。

**Comment by nkmr-jp** [comment]
@waku1123 バグ報告ありがとうございます！
@lirlia さんが修正してくれましたのでcloseします。
